"""
Payment domain model: Pago.

RN-PA08: un pedido puede tener múltiples intentos de pago (1:N pedido→pagos).
Por eso NO hay unique=True en pedido_id — eso violaba la regla de negocio.
La unicidad de idempotency_key garantiza que el mismo intento no se procese dos veces.
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import ForeignKey, Integer, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.shared.models import BaseModel


class Pago(BaseModel):
    """
    Payment entity aligned with ERD v5.

    MercadoPago integration fields (mp_payment_id, mp_status, external_reference)
    are stored here for reconciliation and webhook handling.

    idempotency_key: generated by the caller before initiating payment;
    ensures that retried requests don't create duplicate payments.
    """

    __tablename__ = "payments"

    pedido_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("orders.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        # NO unique=True — RN-PA08 allows multiple payment attempts per order
    )
    monto: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    forma_pago_codigo: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("payment_methods.codigo", ondelete="RESTRICT"),
        nullable=False,
    )
    # MercadoPago integration fields
    mp_payment_id: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    mp_status: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    external_reference: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    # Idempotency key prevents double-charging on retries
    idempotency_key: Mapped[str] = mapped_column(
        String(255), unique=True, nullable=False
    )

    # Relationship back to order
    pedido: Mapped["backend.features.orders.models.Pedido"] = relationship(
        "Pedido",
        back_populates="pagos",
        lazy="select",
    )

    def __repr__(self) -> str:
        return (
            f"<Pago(id={self.id}, pedido_id={self.pedido_id}, "
            f"monto={self.monto}, mp_status={self.mp_status!r})>"
        )
