"""
Payment schemas (Pydantic v2).

PagoCreate — request body for POST /api/v1/pagos (Checkout API)
PagoRead   — response for payment endpoints
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Optional
import uuid

from pydantic import BaseModel, ConfigDict, Field, field_validator


class PagoCreate(BaseModel):
    """
    Request body for POST /api/v1/pagos (Checkout API — direct card charge).

    idempotency_key is generated by the frontend and forwarded to MP.
    """

    pedido_id: int
    card_token: str = Field(
        ..., min_length=1, description="MP card token from frontend SDK"
    )
    payment_method_id: str = Field(
        ..., min_length=1, description="MP payment method ID (e.g. 'visa', 'master')"
    )
    installments: int = Field(default=1, ge=1, description="Number of installments")
    idempotency_key: str = Field(
        ..., description="UUID v4 generated by frontend for idempotency"
    )
    identification_type: str = Field(
        default="DNI", description="Document type (DNI, CUIT, CUIL, LC, LE)"
    )
    identification_number: str = Field(
        ..., min_length=1, description="Document number"
    )

    model_config = ConfigDict(extra="forbid")

    @field_validator("idempotency_key")
    @classmethod
    def _validate_uuid(cls, v: str) -> str:
        try:
            uuid.UUID(v, version=4)
        except (ValueError, AttributeError):
            raise ValueError("idempotency_key must be a valid UUID v4")
        return v


class PagoCreateResponse(BaseModel):
    """
    Response body for POST /api/v1/pagos/ (Checkout API).

    Returned whenever MercadoPago responds with a status, regardless of
    whether the payment was approved, pending, rejected, or cancelled.
    Never returned when MP fails to respond (502 mp_unreachable instead).
    """

    mp_status: str
    mp_id: Optional[str] = None
    status_detail: str
    pago_id: int

    model_config = ConfigDict(from_attributes=False)


class PagoRead(BaseModel):
    id: int
    pedido_id: int
    monto: Decimal
    forma_pago_codigo: str
    mp_payment_id: Optional[str] = None
    mp_status: Optional[str] = None
    idempotency_key: str
    creado_en: datetime
    actualizado_en: datetime
    init_point: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)
