"""
Payment service — MercadoPago integration business logic.

D1: Uses the official `mercadopago` SDK (already in requirements.txt).
D2: idempotency_key is UUID4 generated by the backend (not the client).
D3: external_reference = str(pedido_id) for webhook→order reconciliation.
D4: Webhook processing is synchronous (no background queue for MVP).
D5: Always re-queries MP API to verify payment status (never trusts payload alone).
D6: Idempotency via mp_payment_id — if already approved, returns silently.
D7: PENDIENTE→CONFIRMADO transition delegates to OrderService.transicionar_estado().
D8: Ownership check — only the order owner can initiate a payment.
D10: Retry allowed if last payment is rejected/cancelled; blocked if active.
"""

from __future__ import annotations

import uuid
from typing import Optional

import mercadopago

from config import settings
from features.orders.repository import OrderRepository
from features.orders.service import OrderService
from features.payments.models import Pago
from features.payments.repository import PaymentRepository
from shared.exceptions import BusinessRuleError, ForbiddenError, NotFoundError
from shared.unit_of_work import UnitOfWork


class PaymentService:
    """Stateless service for payment creation, webhook processing, and status queries."""

    def __init__(self) -> None:
        pass

    def _get_sdk(self) -> mercadopago.SDK:
        return mercadopago.SDK(settings.MP_ACCESS_TOKEN)

    def crear_preferencia(
        self,
        user_id: int,
        pedido_id: int,
    ) -> tuple[Pago, str]:
        """
        Create a MercadoPago preference for a PENDIENTE order and register a Pago.

        Returns (pago, init_point) where init_point is the MP checkout URL.

        Raises:
            NotFoundError: pedido_id not found.
            ForbiddenError: pedido belongs to another user (D8).
            BusinessRuleError: pedido is not PENDIENTE, or an active payment exists.
        """
        with UnitOfWork() as uow:
            uow.register_repository("orders", OrderRepository(uow.session))
            uow.register_repository("payments", PaymentRepository(uow.session))

            pedido = uow.orders.find_by_id(pedido_id)
            if pedido is None:
                raise NotFoundError(f"Pedido no encontrado: id={pedido_id}")

            if pedido.user_id != user_id:
                raise ForbiddenError("No tenés permiso para pagar este pedido")

            if pedido.estado_codigo != "PENDIENTE":
                raise BusinessRuleError(
                    f"El pedido está en estado '{pedido.estado_codigo}'. "
                    "Solo se puede pagar un pedido en estado PENDIENTE.",
                    code="conflict",
                )

            active_pago = uow.payments.find_active_by_pedido_id(pedido_id)
            if active_pago is not None:
                raise BusinessRuleError(
                    f"Ya existe un pago activo para este pedido (estado: {active_pago.mp_status}). "
                    "Esperá a que se resuelva antes de reintentar.",
                    code="conflict",
                )

            idempotency_key = str(uuid.uuid4())

            sdk = self._get_sdk()
            preference_data = {
                "items": [
                    {
                        "title": f"Pedido #{pedido_id} — Food Store",
                        "quantity": 1,
                        "unit_price": float(pedido.total),
                        "currency_id": "ARS",
                    }
                ],
                "external_reference": str(pedido_id),
            }
            result = sdk.preference().create(preference_data)
            response = result.get("response", {})
            init_point: str = response.get("init_point", "")

            pago = uow.payments.create_pago(
                pedido_id=pedido_id,
                monto=pedido.total,
                forma_pago_codigo=pedido.forma_pago_codigo,
                idempotency_key=idempotency_key,
            )

            # UoW __exit__ commits both the Pago insert and any implicit session state.
            return pago, init_point

    def procesar_webhook(self, mp_payment_id: str) -> None:
        """
        Process a MercadoPago payment notification.

        Receives a normalised mp_payment_id string (format extraction is the router's job).

        Reconciliation strategy:
        - D6: On duplicate webhooks, find by mp_payment_id — if already approved, return.
        - D5: Always verify status via MP API (never trust the IPN payload alone).
        - Reconcile order via external_reference (pedido_id) returned by the MP API.
        - D7: Trigger PENDIENTE→CONFIRMADO in a separate UoW after payments UoW commits.
        """
        if not mp_payment_id:
            return

        verified_status: str = ""
        pedido_id: Optional[int] = None

        with UnitOfWork() as uow:
            uow.register_repository("payments", PaymentRepository(uow.session))

            # D6 — idempotency: if this mp_payment_id is already approved, do nothing.
            existing = uow.payments.find_by_mp_payment_id(mp_payment_id)
            if existing and existing.mp_status == "approved":
                return

            # D5 — verify real status from MP API; also get external_reference for lookup.
            sdk = self._get_sdk()
            verify_result = sdk.payment().get(mp_payment_id)
            response = verify_result.get("response", {})
            verified_status = response.get("status", "")
            external_reference: str = response.get("external_reference", "")

            if not external_reference:
                return

            try:
                pedido_id = int(external_reference)
            except (ValueError, TypeError):
                return

            # Use the already-found pago (second+ call) or look up by pedido_id (first call).
            pago = existing or uow.payments.find_latest_by_pedido_id(pedido_id)
            if pago is None:
                return

            uow.payments.update_mp_fields(
                pago=pago,
                mp_payment_id=mp_payment_id,
                mp_status=verified_status,
            )
            # UoW __exit__ commits Pago update.

        # D7 — trigger state transition OUTSIDE the payments UoW to avoid nested sessions.
        if verified_status == "approved" and pedido_id is not None:
            try:
                OrderService().transicionar_estado(
                    pedido_id=pedido_id,
                    estado_anterior="PENDIENTE",
                    estado_nuevo="CONFIRMADO",
                    actor_id=None,
                )
            except Exception:
                # Order may already be CONFIRMADO on a duplicate webhook — swallow.
                pass

    def obtener_pago_por_pedido(
        self,
        user_id: int,
        pedido_id: int,
    ) -> Pago:
        """
        Return the latest Pago for a pedido owned by user_id.

        Raises:
            ForbiddenError: pedido belongs to another user.
            NotFoundError: no payments exist yet for the order.
        """
        with UnitOfWork() as uow:
            uow.register_repository("orders", OrderRepository(uow.session))
            uow.register_repository("payments", PaymentRepository(uow.session))

            pedido = uow.orders.find_by_id(pedido_id)
            if pedido is None:
                raise NotFoundError(f"Pedido no encontrado: id={pedido_id}")

            if pedido.user_id != user_id:
                raise ForbiddenError("No tenés permiso para ver el pago de este pedido")

            pago = uow.payments.find_latest_by_pedido_id(pedido_id)
            if pago is None:
                raise NotFoundError("No hay pagos registrados para este pedido")

            return pago
