"""
Payment service — MercadoPago integration business logic.

D1: Uses the official `mercadopago` SDK (already in requirements.txt).
D2: idempotency_key is UUID4 generated by the frontend and forwarded to MP.
D3: external_reference = str(pedido_id) for webhook→order reconciliation.
D4: Webhook processing is synchronous (no background queue for MVP).
D5: Always re-queries MP API to verify payment status (never trusts payload alone).
D6: Idempotency via mp_payment_id — if already approved, returns silently.
D7: PENDIENTE→CONFIRMADO transition delegates to OrderService.transicionar_estado().
D8: Ownership check — only the order owner can initiate a payment.
D10: Retry allowed if last payment is rejected/cancelled; blocked if active.
"""

from __future__ import annotations

from typing import Optional

import mercadopago
from mercadopago.config import RequestOptions

from config import settings
from features.orders.repository import OrderRepository
from features.orders.service import OrderService
from features.payments.models import Pago
from features.payments.repository import PaymentRepository
from shared.exceptions import BusinessRuleError, ForbiddenError, NotFoundError
from shared.unit_of_work import UnitOfWork


class PaymentService:
    """Stateless service for payment creation, webhook processing, and status queries."""

    def __init__(self) -> None:
        pass

    def _get_sdk(self) -> mercadopago.SDK:
        return mercadopago.SDK(settings.MP_ACCESS_TOKEN)

    def crear_pago_api(
        self,
        user_id: int,
        pedido_id: int,
        card_token: str,
        payment_method_id: str,
        installments: int,
        idempotency_key: str,
        identification_type: str = "DNI",
        identification_number: str = "",
    ) -> dict:
        """
        Create a direct card charge via MercadoPago Checkout API.

        Validates order ownership, state, and no active payment.
        On approval, transitions order PENDIENTE → CONFIRMADO.

        Returns:
            {"mp_status": status, "mp_id": mp_payment_id, "status_detail": status_detail}

        Raises:
            NotFoundError: pedido_id not found.
            ForbiddenError: pedido belongs to another user (D8).
            BusinessRuleError: pedido is not PENDIENTE, or an active payment exists,
                or MP payment was rejected/peneded/cancelled.
        """
        with UnitOfWork() as uow:
            uow.register_repository("orders", OrderRepository(uow.session))
            uow.register_repository("payments", PaymentRepository(uow.session))

            pedido = uow.orders.find_by_id(pedido_id)
            if pedido is None:
                raise NotFoundError(f"Pedido no encontrado: id={pedido_id}")

            if pedido.user_id != user_id:
                raise ForbiddenError("No tenés permiso para pagar este pedido")

            if pedido.estado_codigo != "PENDIENTE":
                raise BusinessRuleError(
                    f"El pedido está en estado '{pedido.estado_codigo}'. "
                    "Solo se puede pagar un pedido en estado PENDIENTE.",
                    code="conflict",
                )

            active_pago = uow.payments.find_active_by_pedido_id(pedido_id)
            if active_pago is not None:
                raise BusinessRuleError(
                    f"Ya existe un pago activo para este pedido (estado: {active_pago.mp_status}). "
                    "Esperá a que se resuelva antes de reintentar.",
                    code="conflict",
                )

            # Build payment payload for MP Checkout API
            payment_data = {
                "transaction_amount": float(pedido.total),
                "token": card_token,
                "installments": installments,
                "payment_method_id": payment_method_id,
                "description": f"Pedido #{pedido_id} — Food Store",
                "external_reference": str(pedido_id),
                "identification_type": identification_type,
                "identification_number": identification_number,
            }

            # Forward idempotency key to MP via custom headers in RequestOptions
            request_options = RequestOptions(
                access_token=settings.MP_ACCESS_TOKEN,
                custom_headers={"X-Idempotency-Key": idempotency_key},
            )

            sdk = self._get_sdk()
            result = sdk.payment().create(payment_data, request_options)
            response = result.get("response", {})

            mp_status = response.get("status", "")
            mp_payment_id = response.get("id")
            status_detail = response.get("status_detail", "")

            # Create Pago record
            pago = uow.payments.create_pago(
                pedido_id=pedido_id,
                monto=pedido.total,
                forma_pago_codigo=pedido.forma_pago_codigo,
                idempotency_key=idempotency_key,
            )
            # Update with MP response fields
            if mp_payment_id is not None:
                uow.payments.update_mp_fields(
                    pago=pago,
                    mp_payment_id=str(mp_payment_id),
                    mp_status=mp_status,
                )

            # UoW __exit__ commits the Pago record.

        # D7 — trigger state transition OUTSIDE the payments UoW
        if mp_status == "approved" and mp_payment_id is not None:
            try:
                OrderService().transicionar_estado(
                    pedido_id=pedido_id,
                    estado_anterior="PENDIENTE",
                    estado_nuevo="CONFIRMADO",
                    actor_id=None,
                )
            except Exception:
                # Order may already be CONFIRMADO on a duplicate call — swallow.
                pass
            return {
                "mp_status": mp_status,
                "mp_id": str(mp_payment_id),
                "status_detail": status_detail,
            }

        # Non-approved statuses: return error without state change
        raise BusinessRuleError(
            f"Pago rechazado por MercadoPago: status={mp_status}, detail={status_detail}",
            code=f"payment_{mp_status}",
        )

    def procesar_webhook(self, mp_payment_id: str) -> None:
        """
        Process a MercadoPago payment notification.

        Receives a normalised mp_payment_id string (format extraction is the router's job).

        Reconciliation strategy:
        - D6: On duplicate webhooks, find by mp_payment_id — if already approved, return.
        - D5: Always verify status via MP API (never trust the IPN payload alone).
        - Reconcile order via external_reference (pedido_id) returned by the MP API.
        - D7: Trigger PENDIENTE→CONFIRMADO in a separate UoW after payments UoW commits.
        """
        if not mp_payment_id:
            return

        verified_status: str = ""
        pedido_id: Optional[int] = None

        with UnitOfWork() as uow:
            uow.register_repository("payments", PaymentRepository(uow.session))

            # D6 — idempotency: if this mp_payment_id is already approved, do nothing.
            existing = uow.payments.find_by_mp_payment_id(mp_payment_id)
            if existing and existing.mp_status == "approved":
                return

            # D5 — verify real status from MP API; also get external_reference for lookup.
            sdk = self._get_sdk()
            verify_result = sdk.payment().get(mp_payment_id)
            response = verify_result.get("response", {})
            verified_status = response.get("status", "")
            external_reference: str = response.get("external_reference", "")

            if not external_reference:
                return

            try:
                pedido_id = int(external_reference)
            except (ValueError, TypeError):
                return

            # Use the already-found pago (second+ call) or look up by pedido_id (first call).
            pago = existing or uow.payments.find_latest_by_pedido_id(pedido_id)
            if pago is None:
                return

            uow.payments.update_mp_fields(
                pago=pago,
                mp_payment_id=mp_payment_id,
                mp_status=verified_status,
            )
            # UoW __exit__ commits Pago update.

        # D7 — trigger state transition OUTSIDE the payments UoW to avoid nested sessions.
        if verified_status == "approved" and pedido_id is not None:
            try:
                OrderService().transicionar_estado(
                    pedido_id=pedido_id,
                    estado_anterior="PENDIENTE",
                    estado_nuevo="CONFIRMADO",
                    actor_id=None,
                )
            except Exception:
                # Order may already be CONFIRMADO on a duplicate webhook — swallow.
                pass

    def obtener_pago_por_pedido(
        self,
        user_id: int,
        pedido_id: int,
    ) -> Pago:
        """
        Return the latest Pago for a pedido owned by user_id.

        Raises:
            ForbiddenError: pedido belongs to another user.
            NotFoundError: no payments exist yet for the order.
        """
        with UnitOfWork() as uow:
            uow.register_repository("orders", OrderRepository(uow.session))
            uow.register_repository("payments", PaymentRepository(uow.session))

            pedido = uow.orders.find_by_id(pedido_id)
            if pedido is None:
                raise NotFoundError(f"Pedido no encontrado: id={pedido_id}")

            if pedido.user_id != user_id:
                raise ForbiddenError("No tenés permiso para ver el pago de este pedido")

            pago = uow.payments.find_latest_by_pedido_id(pedido_id)
            if pago is None:
                raise NotFoundError("No hay pagos registrados para este pedido")

            return pago
