"""Cookie helpers for browser authentication.

Tokens are still generated by AuthService. This module only controls how the
router transports them to/from the browser.
"""

from fastapi import Response

from config import settings
from features.auth.schemas import TokenPairResponse


def set_auth_cookies(response: Response, tokens: TokenPairResponse) -> None:
    """Set access and refresh HttpOnly cookies using configured dev defaults."""
    response.set_cookie(
        key=settings.AUTH_COOKIE_ACCESS_NAME,
        value=tokens.access_token,
        max_age=settings.JWT_ACCESS_TOKEN_EXPIRE_MINUTES * 60,
        path=settings.AUTH_COOKIE_ACCESS_PATH,
        secure=settings.AUTH_COOKIE_SECURE,
        httponly=True,
        samesite=settings.AUTH_COOKIE_SAMESITE,
    )
    response.set_cookie(
        key=settings.AUTH_COOKIE_REFRESH_NAME,
        value=tokens.refresh_token,
        max_age=settings.JWT_REFRESH_TOKEN_EXPIRE_DAYS * 24 * 60 * 60,
        path=settings.AUTH_COOKIE_REFRESH_PATH,
        secure=settings.AUTH_COOKIE_SECURE,
        httponly=True,
        samesite=settings.AUTH_COOKIE_SAMESITE,
    )


def clear_auth_cookies(response: Response) -> None:
    """Clear auth cookies. Paths must match the paths used when setting them."""
    response.delete_cookie(
        key=settings.AUTH_COOKIE_ACCESS_NAME,
        path=settings.AUTH_COOKIE_ACCESS_PATH,
        secure=settings.AUTH_COOKIE_SECURE,
        httponly=True,
        samesite=settings.AUTH_COOKIE_SAMESITE,
    )
    response.delete_cookie(
        key=settings.AUTH_COOKIE_REFRESH_NAME,
        path=settings.AUTH_COOKIE_REFRESH_PATH,
        secure=settings.AUTH_COOKIE_SECURE,
        httponly=True,
        samesite=settings.AUTH_COOKIE_SAMESITE,
    )
