export interface PagoCreate {
  pedido_id: number;
}

export interface PagoRead {
  id: number;
  pedido_id: number;
  monto: string; // Decimal serialized as string from backend
  forma_pago_codigo: string;
  mp_payment_id: string | null;
  mp_status: string | null;
  idempotency_key: string;
  creado_en: string;
  actualizado_en: string;
  init_point: string | null;
}

/** Inline payment request for Secure Fields flow. */
export interface PaymentCreateRequest {
  pedido_id: number;
  card_token: string;
  payment_method_id: string;
  installments: number;
  idempotency_key: string; // UUID, generated by frontend
  identification_type: string;
  identification_number: string;
}

/** Response from the inline payment API. */
export interface PaymentResponse {
  mp_status: string;
  mp_id: string | null;
  status_detail: string | null;
  order_id?: number;
}

/** Request to transition an order state via FSM. */
export interface TransicionarRequest {
  estado_codigo_destino: string;
  motivo?: string;
}

/** Response from the order state transition API. */
export interface TransicionarResponse {
  pedido_id: number;
  estado_anterior: string;
  estado_nuevo: string;
  historial: Array<{
    id: number;
    estado_anterior: string | null;
    estado_nuevo: string;
    actor: string | null;
    motivo: string | null;
    creado_en: string;
  }>;
}
